### ISSUE TITLE
Consider upstreaming the necessary pieces to hlint

### ISSUE THREAD

**Issue by ndmitchell** [pbrisbin/codeclimate-hlint#11]
It seems you are using HLint the library, then tweaking the output to match the code-climate requirements. At the same time you've added some configuration support, which somewhat matches that which will be in the new version of HLint. What would it take to move everything into HLint? What is missing? Is that feasible? I'm not adverse to a little bit of custom JSON generation in HLint.

**Comment by pbrisbin** [comment]
Hi @ndmitchell thanks for reaching out. I'm also a Code Climate engineer and would be really excited to work with you on this stuff.

> What would it take to move everything into HLint? What is missing? Is that feasible?

On the one end of the spectrum would be what we call "native" engine support. This means everything it takes to run as an engine is present in the upstream project, with no need for a `codeclimate-x` wrapper project at all. For obvious reasons, this is our ideal.

At a high level, this requires:

- The tool can output in our format (e.g. by adding a `--format` option)
- The tool can change its behavior based on what users can configure in their `.codeclimate.yml`s (at a minimum, we need to specify the files operated on)
- The tool can be docker-built as an engine image ([example](https://github.com/presidentbeef/brakeman/blob/master/Dockerfile))

In general, this just means it's compliant with the [SPEC](https://github.com/codeclimate/spec/blob/master/SPEC.md)

At the other end of the spectrum would be this project as it is now, doing all the required building and adaptive work to not need any changes in the upstream hlint project.

Somewhere in the middle might be adding that `--format` option and some better support for the configuration points we need, but still keeping this project as the glue/shim.

Do you have a sense of how far you'd like to move along that spectrum?

**Comment by ndmitchell** [comment]
Regarding the steps:

* Adding a `--format` - that seems perfectly reasonable, and better done inside HLint than round the outside.
* Configuring based on `.codeclimate.yml` - in HEAD I configure based on `.hlint.yaml`. You could imagine also being able to suck that configuration out of `.codeclimate.yml`, or just sucking the files to operate on out of there, and the rest from `.hlint.yaml`. I'm sure I can at least do the minimum.
* For docker building, I don't know much about that area, but am happy to take a patch adding it.

So it seems like a graduated approach makes sense - first producing the right output, and then see how it goes.

**Comment by pbrisbin** [comment]
That sounds great to me.

I can absolutely handle the docker side of things. In fact, we can handle configuration as part of that as well, if it's convenient: there will be some executable (probably shell) that's invoked when the docker image is run, so that executable can easily read our configuration (provided via a volume-mount at `/config.json`), and write an equivalent `.hlint.yml` before running the `hlint` process.

I have ~~two~~ three small questions on that front:

- Can the list of files to operate on be provided via `.hlint.yml`?
- Is it true or false that everything configurable via `.hlint.yml` has equivalent CLI flags?
- Can the `.hlint.yml` be read from some other arbitrary path by a CLI flag?

**Comment by pbrisbin** [comment]
FYI: https://github.com/ndmitchell/hlint/pull/383

**Comment by ndmitchell** [comment]
Answers to your questions:

* You can now put command line flags in `.hlint.yaml`, so in that sense you can provide a list of files and any arbitrary flags.
* You can pass the contents of `.hlint.yaml` on the command line, so in that sense anything in the file can be provided as a command line - but it's a bit grim.
* Yes, you can control which `.hlint.yaml` is picked with a flag.

**Comment by pbrisbin** [comment]
This has been merged!
