### ISSUE TITLE
CPP options

### ISSUE THREAD

**Issue by Bodigrim** [pbrisbin/codeclimate-hlint#9]
Hi. I am trying to integrate https://github.com/Bodigrim/arithmoi with `codeclimate-hlint`. But I get much less warnings than expected (https://codeclimate.com/github/Bodigrim/arithmoi/issues?category=&engine=hlint), presumably due to the heavy use of CPP in my code. 

Is there a way to provide additional options in `.codeclimate.yml`? On my local machine I invoke HLint as 

```
hlint --cpp-include=$(stack path --ghc-paths)/ghc-7.10.3/lib/ghc-7.10.3/include --cpp-define="MIN_VERSION_array(a,b,c)=1" --cpp-define="MIN_VERSION_base(a,b,c)=1"
```

It would be great to achieve the same effect using your engine.

Thanks a ton.

**Comment by pbrisbin** [comment]
Great question. Unfortunately, there isn't currently a means to configure the hlint run via the engine, but that's definitely something I'd like to see and am planning to add.

Even with that, you might run into trouble with your first option:
- The syntax in `.codeclimate.yml` wouldn't support `$( )` expansion (clearly)
- The engine only has access to the project directory, so if `stack path --ghc-paths` points to somewhere outside, it won't work

I'm not sure of a good solution to that one.

**Comment by Bodigrim** [comment]
Thanks for quick answer. 
No problem, I can copy `lib/ghc-7.10.3/include` into project directory to work around both troubles.
